[features]
seeds = true
skip-lint = false

[programs.devnet]
pirate_faucet = "6yMWpBc4YFXCyuN3dEmcjPYBcYfx12oPE7rzGvbxYX96"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/joesol/.config/solana/id.json"

[scripts]
upload-json = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/upload-json.test.ts"
create-assets = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-assets.test.ts"
master = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/master.test.ts"